import { useState, type ReactNode } from 'react'
import { Activity, Bell, ChevronDown, Database, FileText, Globe2, Layers3, Map, Menu, Mic, Plus, Search, Settings, ShieldCheck, Sparkles, Upload, Waves, X } from 'lucide-react'
import './App.css'
import AuthScreen from './AuthScreen'

type Page = 'home' | 'analysis' | 'history'
const steps = ['Query received', 'Input validated', 'Metadata extracted', 'Task identified', 'Agents selected', 'Evidence verified', 'Confidence calculated']
const suggestions = ['What changed between 2023 and 2025?', 'Where are the newly constructed buildings?', 'Compare optical and SAR evidence']

export default function App() {
  const [authenticated, setAuthenticated] = useState(() => localStorage.getItem('satquery_auth') === 'true')
  const [page, setPage] = useState<Page>('home')
  const [query, setQuery] = useState('Identify significant changes between 2023 and 2025, show where the changes occurred, determine whether built-up area increased, and explain how optical and SAR evidence support the conclusion.')
  const [running, setRunning] = useState(false)
  const [trace, setTrace] = useState(true)
  const [menu, setMenu] = useState(false)
  const run = () => { setRunning(true); setPage('analysis'); window.setTimeout(() => setRunning(false), 1400) }
  const signIn = () => { localStorage.setItem('satquery_auth', 'true'); setAuthenticated(true) }
  if (!authenticated) return <AuthScreen onAuthenticated={signIn} />
  return <div className="app-shell">
    <aside className={`sidebar ${menu ? 'open' : ''}`}><div className="brand"><div className="brand-mark"><Waves size={18} /></div><div><strong>SatQuery</strong><span>AI / GEOINT PLATFORM</span></div><button className="close-menu" onClick={() => setMenu(false)}><X size={18} /></button></div><div className="workspace-label">WORKSPACE <span>›</span></div><Nav active={page === 'home'} icon={<Activity size={17} />} text="Command center" onClick={() => setPage('home')} /><Nav active={page === 'analysis'} icon={<Sparkles size={17} />} text="New analysis" badge="2" onClick={() => setPage('analysis')} /><Nav icon={<Map size={17} />} text="GIS explorer" /><Nav icon={<Layers3 size={17} />} text="Timeline" /><div className="workspace-label section-label">LIBRARY</div><Nav active={page === 'history'} icon={<Database size={17} />} text="Analysis history" onClick={() => setPage('history')} /><Nav icon={<FileText size={17} />} text="Reports" badge="4" /><Nav icon={<Bell size={17} />} text="Alerts" /><div className="sidebar-bottom"><div className="status-line"><i /> AI services operational</div><Nav icon={<Settings size={17} />} text="Settings" /><div className="profile"><div className="avatar">AS</div><div><strong>Ananya Sharma</strong><span>Research analyst</span></div><ChevronDown size={15} /></div></div></aside>
    <main className="main-content"><header className="topbar"><button className="menu-button" onClick={() => setMenu(true)}><Menu size={20} /></button><div className="breadcrumb"><span>Workspace</span><b>/</b><strong>{page === 'home' ? 'Command center' : page === 'history' ? 'Analysis history' : 'New analysis'}</strong></div><div className="top-actions"><div className="live-pill"><i /> LIVE DEMO</div><button className="icon-button"><Bell size={18} /></button><button className="user-chip" onClick={() => { localStorage.removeItem('satquery_auth'); setAuthenticated(false) }}><span className="avatar small">AS</span><ChevronDown size={15} /></button></div></header>
      {page === 'home' && <Home onStart={() => setPage('analysis')} onHistory={() => setPage('history')} />}
      {page === 'analysis' && <Analysis query={query} setQuery={setQuery} running={running} run={run} trace={trace} setTrace={setTrace} />}
      {page === 'history' && <History onNew={() => setPage('analysis')} />}
    </main></div>
}

function Nav({ icon, text, badge, active, onClick }: { icon: ReactNode; text: string; badge?: string; active?: boolean; onClick?: () => void }) { return <button className={`nav-item ${active ? 'active' : ''}`} onClick={onClick}>{icon}{text}{badge && <span className="nav-badge">{badge}</span>}</button> }
function Metric({ icon, label, value, delta }: { icon: ReactNode; label: string; value: string; delta: string }) { return <div className="metric panel"><div className="metric-icon">{icon}</div><span>{label}</span><div className="metric-value">{value}<small>{delta}</small></div></div> }
function Thumb({ color }: { color: string }) { return <div className={`analysis-thumb ${color}`} /> }
function Row({ title, type, confidence, color }: { title: string; type: string; confidence: string; color: string }) { return <div className="analysis-row"><Thumb color={color} /><div><strong>{title}</strong><span>{type}</span></div><div className="confidence"><b>{confidence}</b><span>confidence</span></div><em>→</em></div> }
function Quick({ icon, title, text, onClick }: { icon: ReactNode; title: string; text: string; onClick: () => void }) { return <button className="quick-action" onClick={onClick}><div className="quick-icon">{icon}</div><div><strong>{title}</strong><span>{text}</span></div><em>→</em></button> }
function PanelTitle({ label, title, action }: { label: string; title: string; action?: ReactNode }) { return <div className="panel-heading"><div><p className="eyebrow muted">{label}</p><h3>{title}</h3></div>{action}</div> }

function Home({ onStart, onHistory }: { onStart: () => void; onHistory: () => void }) { return <><section className="hero"><div><p className="eyebrow"><i /> SATELLITE INTELLIGENCE / 01</p><h1>Ask the satellite.<br /><em>Get the evidence.</em></h1><p className="hero-copy">An agentic vision-language assistant for understanding Earth observation data with clarity, confidence, and proof.</p><button className="primary-button" onClick={onStart}><Plus size={18} /> Start an analysis</button></div><div className="orbital"><div className="orbit" /><div className="orbit second" /><div className="earth"><b /><b /><b /></div><span>28.6° N</span><span>77.2° E</span></div></section><div className="section-head"><div><p className="eyebrow muted">OVERVIEW</p><h2>Your intelligence workspace</h2></div><button className="text-button" onClick={onHistory}>View history <b>→</b></button></div><section className="metric-grid"><Metric icon={<Sparkles size={18} />} label="Total analyses" value="128" delta="+18.4%" /><Metric icon={<Globe2 size={18} />} label="Images processed" value="482" delta="+24.1%" /><Metric icon={<Layers3 size={18} />} label="Changes detected" value="76" delta="+9.8%" /><Metric icon={<FileText size={18} />} label="Reports generated" value="34" delta="+12.0%" /></section><section className="workspace-grid"><div className="panel"><PanelTitle label="RECENT ACTIVITY" title="Analyses worth revisiting" action={<button className="icon-button subtle"><Search size={17} /></button>} /><Row title="Urban growth assessment / Bengaluru" type="Optical + SAR · 2023 — 2025" confidence="94%" color="cyan" /><Row title="Agricultural water stress scan" type="Single image · Sentinel-2" confidence="87%" color="yellow" /><Row title="Coastal change monitoring" type="Multi-temporal · 6 scenes" confidence="91%" color="green" /></div><div className="panel"><PanelTitle label="SHORTCUTS" title="Start with a workflow" /><Quick icon={<Upload size={18} />} title="Single image" text="Ask questions of one scene" onClick={onStart} /><Quick icon={<Layers3 size={18} />} title="Change intelligence" text="Compare dates and find change" onClick={onStart} /><Quick icon={<Waves size={18} />} title="Optical + SAR" text="Fuse modalities for evidence" onClick={onStart} /></div></section></> }

function Source({ year, modality, color }: { year: string; modality: string; color: string }) { return <div className="source-card"><div className={`source-image ${color}`}><span>{year}</span><b>{modality}</b></div><div className="source-meta"><strong>{year} {modality.toLowerCase()}</strong><span>Sentinel · 10 m · GeoTIFF</span></div><ShieldCheck size={15} className="verified" /></div> }
function Analysis({ query, setQuery, running, run, trace, setTrace }: { query: string; setQuery: (v: string) => void; running: boolean; run: () => void; trace: boolean; setTrace: (v: boolean) => void }) { return <><section className="analysis-header"><div><p className="eyebrow"><i /> NEW ANALYSIS / DEMO DATA</p><h1>Multi-temporal intelligence</h1><p>2023 → 2025 · Bengaluru urban edge · 4 source images</p></div><div className="header-actions"><button className="secondary-button"><FileText size={16} /> Generate report</button><button className="primary-button small" onClick={run}><Sparkles size={16} /> {running ? 'Running...' : 'Run analysis'}</button></div></section><section className="analysis-layout"><div className="analysis-left"><div className="query-card panel"><div className="card-label"><Sparkles size={15} /> NATURAL LANGUAGE QUERY <span>EXPERT <ChevronDown size={13} /></span></div><textarea value={query} onChange={e => setQuery(e.target.value)} /> <div className="suggestions">{suggestions.map(s => <button key={s} onClick={() => setQuery(s)}>{s}</button>)}</div><div className="query-footer"><button className="icon-button subtle"><Mic size={17} /></button><small>English · Voice input ready</small><button className="send-button" onClick={run}>Analyze <Sparkles size={15} /></button></div></div><div className="source-panel panel"><PanelTitle label="INPUT SOURCES" title="Evidence stack  ·  4 / 4" action={<button className="text-button">Manage →</button>} /><div className="source-grid"><Source year="2023" modality="OPTICAL" color="teal" /><Source year="2023" modality="SAR" color="purple" /><Source year="2025" modality="OPTICAL" color="orange" /><Source year="2025" modality="SAR" color="blue" /></div></div></div><div className="analysis-right"><MapPanel /><Result /><div className="trace-section"><button className="trace-toggle" onClick={() => setTrace(!trace)}><div><p className="eyebrow muted">AUDITABLE EXECUTION</p><h3>Agent execution trace</h3></div><ChevronDown className={trace ? 'rotated' : ''} size={19} /></button>{trace && <div className="trace-grid">{steps.map((s, i) => <div className="trace-step" key={s}><div className="trace-number">{i < 6 ? '✓' : i + 1}</div><span>{s}</span><small>{i < 4 ? `${(i + 1) * .4 + .2}s` : 'ready'}</small></div>)}</div>}</div></div></section></> }
function MapPanel() { return <div className="map-panel panel"><div className="map-toolbar"><div><span className="live-dot" /> CHANGE MAP <small>FUSED EVIDENCE</small></div><div className="map-controls"><button>−</button><button>+</button><button><Layers3 size={15} /></button></div></div><div className="map-canvas"><div className="map-grid" /><div className="road a" /><div className="road b" /><div className="road c" /><div className="change-zone one"><span>01</span></div><div className="change-zone two"><span>02</span></div><div className="map-coords">12°58' N&nbsp;&nbsp; 77°35' E</div><div className="map-legend"><span><i /> Detected change</span><span><i /> Context</span></div></div><div className="map-footer"><span><Map size={15} /> Bengaluru, Karnataka</span><span>EPSG:4326 · 10 m resolution</span></div></div> }
function Result() { return <div className="result-card panel"><div className="result-title"><div><p className="eyebrow muted">AI RESULT / FUSED CONCLUSION</p><h2>Built-up area increased significantly</h2></div><div className="confidence-ring"><strong>94</strong><span>%</span></div></div><p className="result-copy">New construction is concentrated in the northern and eastern portions of the scene. Both optical texture and SAR backscatter support the detection.</p><div className="evidence-stats"><div><span>AFFECTED AREA</span><strong>18.6 ha</strong></div><div><span>CHANGE REGIONS</span><strong>2 significant</strong></div><div><span>EVIDENCE QUALITY</span><strong className="high">High</strong></div></div><div className="result-actions"><button className="secondary-button">Show evidence</button><button className="secondary-button">Why?</button><button className="secondary-button icon-only"><FileText size={16} /></button></div></div> }
function History({ onNew }: { onNew: () => void }) { return <section className="history-view"><div className="analysis-header"><div><p className="eyebrow"><i /> LIBRARY / HISTORY</p><h1>Analysis history</h1><p>Every answer, source, and evidence trail in one place.</p></div><button className="primary-button" onClick={onNew}><Plus size={18} /> New analysis</button></div><div className="history-toolbar panel"><div className="search-field"><Search size={17} /><input placeholder="Search analyses, locations, or queries" /></div><button className="secondary-button">All types <ChevronDown size={15} /></button><button className="secondary-button">Newest first <ChevronDown size={15} /></button></div><div className="history-table panel"><div className="table-head"><span>ANALYSIS</span><span>TYPE</span><span>CONFIDENCE</span><span>DATE</span></div><Row title="Urban growth assessment / Bengaluru" type="Optical + SAR · Multi-temporal" confidence="94%" color="cyan" /><Row title="Agricultural water stress scan" type="Single image · VQA" confidence="87%" color="yellow" /><Row title="Coastal change monitoring" type="Multi-temporal · Change" confidence="91%" color="green" /><Row title="Water body grounding / Mysuru" type="Grounding · GIS" confidence="89%" color="blue" /></div></section> }
