type DashboardProps = { onStart: () => void; onHistory: () => void; onReports: () => void }

export default function Dashboard({ onStart, onHistory, onReports }: DashboardProps) {
  return <section className="dashboard-home">
    <div className="dashboard-heading"><div><div className="breadcrumb">MISSION CONTROL / OVERVIEW</div><h1>Analysis overview</h1><p>Your remote-sensing workspace at a glance.</p></div><button className="analyze-button" onClick={onStart}>＋ New analysis <span>→</span></button></div>
    <div className="stat-grid"><div className="stat-card"><span>IMAGES ANALYZED</span><strong>1,284</strong><small>↑ 18% this month</small></div><div className="stat-card accent"><span>CHANGE ANALYSES</span><strong>438</strong><small>Bi-temporal studies</small></div><div className="stat-card"><span>VQA QUERIES</span><strong>721</strong><small>Across 42 sessions</small></div><div className="stat-card"><span>REPORTS GENERATED</span><strong>126</strong><small>12 awaiting review</small></div></div>
    <div className="dashboard-grid"><div className="dashboard-panel recent-panel"><div className="dashboard-panel-heading"><div><span>RECENT ANALYSES</span><small>Continue where you left off</small></div><button onClick={onHistory}>View all →</button></div><button className="analysis-row" onClick={onStart}><span className="analysis-icon flood">⇄</span><div><strong>Floodplain expansion · Bengaluru</strong><small>Change detection · 2 images · 8 minutes ago</small></div><b>92%</b></button><button className="analysis-row" onClick={onStart}><span className="analysis-icon urban">▦</span><div><strong>Building inventory · Whitefield</strong><small>Grounding · Optical · Yesterday</small></div><b>88%</b></button><button className="analysis-row" onClick={onStart}><span className="analysis-icon crop">✳</span><div><strong>Crop health survey · Mandya</strong><small>Agriculture · Multispectral · 2 days ago</small></div><b>84%</b></button></div><div className="dashboard-panel health-panel"><div className="dashboard-panel-heading"><div><span>SYSTEM STATUS</span><small>All core services</small></div><i className="health-live">● LIVE</i></div><div className="health-row"><span>Firebase Authentication</span><b>Operational</b></div><div className="health-row"><span>Firestore & Storage</span><b>Operational</b></div><div className="health-row"><span>Agent controller</span><b>Demo ready</b></div><div className="health-row"><span>Model service</span><b className="muted-status">Endpoint needed</b></div><button className="health-action" onClick={onReports}>Open reports and exports →</button></div></div>
    <div className="dashboard-footer-note"><span>✦</span><div><strong>Ready for your next observation</strong><small>Upload optical, SAR, or bi-temporal imagery and let SatQuery route the analysis.</small></div><button onClick={onStart}>Start analysis →</button></div>
  </section>
}
